apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:   #selector that specifies how to identify Pods it can acquire
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5


#->ReplicaSet as a Horizontal Pod Autoscaler Target
#A ReplicaSet can also be a target for Horizontal Pod Autoscalers (HPA).
# That is, a ReplicaSet can be auto-scaled by an HPA. Here is an example HPA targeting the 
# ReplicaSet we created in the previous example.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

#Alternatively, you can use the kubectl autoscale command to accomplish the same (and it's easier!)
# kubectl autoscale rs frontend --max=10 --min=3 --cpu-percent=50